---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: download wordpress
      get_url:
        url: "https://wordpress.org/latest.zip"
        dest: /tmp/

    - name: unzip wordpress
      unarchive:
        src: /tmp/wordpress-5.2.3.zip
        dest: /tmp
        remote_src: yes
      ignore_errors: true





    