---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: add multiple users
      user:
        name: "{{item}}"
        state: present
      with_items:
        - bob
        - junai
        - kemal
        - volodya
        
