---
- name: create a simple static website with apache
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: make sure apache is installed and latest version
      yum: 
        name: "{{item}}"
        state: latest
      with_items:
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-mysql
    
    - name: start and enable apache
      service:
        name: "{{item}}"
        state: started
      with_items:
        - httpd
        - mariadb



    - name: download latest wordpress
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip

    - name: install packages
      yum:
        name: "{{item}}"
        state: installed
      with_items:
        - 

    
   
  handlers:
    - name: restart my apache
      service: name=httpd state=restarted




