---
- name: create a file and directory, assign to user talant
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: add user talant
      user:
        name: talant
        groups: wheel
        append: yes

    - name: create a file
      file:
        path: /tmp/talant-file.txt
        mode: u=r
        owner: talant
        