---
- hosts: la1
  become: yes
  tasks:
    - name: install jdk
      yum:
        name: java-1.8.0-openjdk-devel
        state: latest

    - name: Add Jenkins repo
      yum_repository:
        name: jenkins.repo
        description: Jenkins REPO
        baseurl: http://pkg.jenkins-ci.org/redhat-stable/
